name = "Cobble Aero Pack"
author = "jazck"
version = "1.0.0\1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "170a3c2f422ab02df292d2520deb328bdb5cb8cd11a157d0511722ef14aad8a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
