name = "Cobble Aero Pack"
author = "jazck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c90449dd7700c00558ad568ac2a55432280b4f402b23045e85da81d3ec96291"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
