name = "Cobble Aero Pack"
author = "jazck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d87ad2166b5bca0aadc9111114727dc8ff115d0c962d746b076847e6725271"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
